version: '3.8'

services:
  # Elasticsearch service (optional - use if not connecting to external ES)
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: symptom-minder-elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  # SymptomMinder FastMCP Server
  symptom-minder:
    build: .
    container_name: symptom-minder
    env_file:
      - .env
    stdin_open: true
    tty: true
    depends_on:
      elasticsearch:
        condition: service_healthy

volumes:
  es_data:
