[project]
name = "SymptomMinder"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.15",
    "anthropic>=0.61.0",
    "elasticsearch>=9.1.0",
    "fastmcp>=2.11.1",
]
